seed_everything: 42
trainer:
  logger: 
      class_path: pytorch_lightning.loggers.CSVLogger
      init_args:
          save_dir: vqgae/experiments/training/logs/
          name: vqgae
          version: 1
  gradient_clip_val: 1.0
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 100
  log_every_n_steps: 1000
  precision: 16
  detect_anomaly: false
model:
  max_atoms: 51
  batch_size: 500
  num_conv_layers: 5
  vector_dim: 512
  num_mha_layers: 8
  num_agg_layers: 2
  num_heads_encoder: 16
  num_heads_decoder: 16
  dropout: 0.2
  bias: true
  init_values: 0.0005
  lr: 0.0002
  task: train
  shuffle_graph: false
  positional_bias: false
  reparam: false
  class_categories: [38, 29, 21, 25, 16, 13, 50, 13]
data:
  path_train_predict: data/chembl/bfs/final/chembl_train.sdf
  path_val: data/chembl/bfs/final/chembl_val.sdf
  tmp_folder: vqgae/experiments/training/tmp/
  tmp_name: chembl
  properties_names: {
  "Hetero Atom Count": "class",
  "acceptorcount": "class",
  "donorcount": "class",
  "Chiral center count": "class",
  "Ring count": "class",
  "Hetero ring count": "class",
  "Rotatable bond count": "class",
  "Aromatic ring count": "class",
  }
  num_workers: 0
  pin_memory: True
  drop_last: True
vqgae_lr_monitor:
  logging_interval: epoch
vqgae_model_checkpoint:
  dirpath: vqgae/experiments/training/weights/
  filename: ${trainer.logger.init_args.name}
  monitor: train_loss
  mode: min