"""RDKit-backed structure filters used in inverse-QSAR pipelines.

Wraps the standard medchem-alert workflows from the lab notebooks
(research/experiments/inverse_qsar/ga_with_fixed_scaffold.ipynb) so users
don't reimplement them.

`rdkit` is a hard dep of this module — import it lazily so users who only
need encode/decode don't pay the import cost.
"""

from __future__ import annotations

from collections.abc import Iterable

from chython.containers import MoleculeContainer

# Medchem alert SMARTS used in the published scaffold-constrained run:
#   - macrocycles (8 .. 17-atom rings)
#   - peroxide and disulfide
#   - tertiary carbocations
#   - heteroatom-heteroatom singles (N-N, N-S)
#   - alkynes
SMARTS_ALERTS: tuple[str, ...] = (
    "[*;r8]",
    "[*;r9]",
    "[*;r10]",
    "[*;r11]",
    "[*;r12]",
    "[*;r13]",
    "[*;r14]",
    "[*;r15]",
    "[*;r16]",
    "[*;r17]",
    "[#8][#8]",  # peroxide
    "[#6;+]",  # carbocation
    "[#16][#16]",  # disulfide
    "[#7;!n][S;!$(S(=O)=O)]",  # N-S (excl. sulfonamides)
    "[#7;!n][#7;!n]",  # N-N (non-aromatic)
    "C#C",  # alkyne
)


def mol_to_rdkit(
    mol: MoleculeContainer, *, compute_2d: bool = False, clear_atom_maps: bool = True
):
    """Convert a chython `MoleculeContainer` to an RDKit `Mol`.

    Wraps the boilerplate that appears in every notebook:
      - copy + kekule (RDKit doesn't accept chython's aromatic order 4)
      - `mol.to_rdkit(...)`
      - optional 2D coordinate computation
      - optional atom-map number reset

    :param compute_2d:        run `rdkit.Chem.AllChem.Compute2DCoords` on the result.
    :param clear_atom_maps:   set every atom's `AtomMapNum` to 0 (the default
                              is True because chython preserves the per-atom
                              numbering and that bleeds into SMILES output).
    """
    from rdkit.Chem import AllChem  # lazy

    tmp = mol.copy()
    tmp.kekule()
    rdkit_mol = tmp.to_rdkit(keep_mapping=False, keep_hydrogens=False)
    if compute_2d:
        AllChem.Compute2DCoords(rdkit_mol, clearConfs=True)
    if clear_atom_maps:
        for atom in rdkit_mol.GetAtoms():
            atom.SetAtomMapNum(0)
    return rdkit_mol


def rdkit_to_mol(rdkit_mol) -> MoleculeContainer:
    """Convert an RDKit `Mol` to a chython `MoleculeContainer`.

    Goes via canonical SMILES (RDKit produces aromatic SMILES that chython
    can re-parse cleanly). Fixes the common case where someone hands you an
    RDKit Mol — from a generative model, a docking program, a database
    query — and you want it back in VQGAE's native format.

    The result is `canonicalize()`-d but **not** kekulized; call `mol.kekule()`
    yourself if you need explicit single/double bonds (e.g. before passing
    through `preprocess_molecule`).
    """
    from rdkit import Chem  # lazy

    smi = Chem.MolToSmiles(rdkit_mol)
    return smiles_to_mol(smi, fallback_to_rdkit=False)


def smiles_to_mol(smi: str, *, fallback_to_rdkit: bool = True) -> MoleculeContainer:
    """Robust SMILES parser: chython first, fall back to RDKit canonicalisation.

    chython is strict about valences and Kekulé form. SMILES generated by
    RDKit / OpenEye / SMILES drawers can use conventions chython rejects
    (e.g. some aromatic forms, certain stereo annotations). When that
    happens, this helper re-parses with RDKit and feeds the canonical
    SMILES back to chython.

    :param smi: input SMILES.
    :param fallback_to_rdkit: if False, raise on chython's failure instead
        of trying RDKit. Useful when you specifically want to know that
        a particular dialect tripped chython.
    :raises ValueError: if both chython and RDKit fail to parse the input.
    """
    from chython import smiles as _chython_smiles  # lazy

    chython_err: Exception | None = None
    try:
        m = _chython_smiles(smi)
        m.canonicalize()
        return m
    except Exception as exc:
        if not fallback_to_rdkit:
            raise
        chython_err = exc

    from rdkit import Chem  # lazy

    rdkit_mol = Chem.MolFromSmiles(smi)
    if rdkit_mol is None:
        raise ValueError(
            f"could not parse SMILES with chython or RDKit: {smi!r}"
        ) from chython_err
    canonical = Chem.MolToSmiles(rdkit_mol)
    m = _chython_smiles(canonical)
    m.canonicalize()
    return m


def check_smarts_alerts(rdkit_mol, alerts: Iterable[str] = SMARTS_ALERTS) -> bool:
    """Return True iff the molecule has *no* match against any alert SMARTS.

    A False return means the molecule should be filtered out.
    """
    from rdkit import Chem  # lazy

    for smarts in alerts:
        pattern = Chem.MolFromSmarts(smarts)
        if pattern is None:
            continue
        if rdkit_mol.HasSubstructMatch(pattern):
            return False
    return True


def pains_brenk_nih_filter(
    rdkit_mol,
    catalogs: tuple[str, ...] = ("PAINS", "NIH", "BRENK"),
) -> bool:
    """Return True iff the molecule passes (i.e. matches *no* catalog entry).

    Uses RDKit's bundled `FilterCatalog`. Catalog names are
    case-sensitive attributes on `FilterCatalogParams.FilterCatalogs`
    (`PAINS`, `BRENK`, `NIH`, `ZINC`, `CHEMBL`, …).
    """
    from rdkit.Chem.FilterCatalog import FilterCatalog, FilterCatalogParams  # lazy

    params = FilterCatalogParams()
    for name in catalogs:
        params.AddCatalog(getattr(FilterCatalogParams.FilterCatalogs, name))
    catalog = FilterCatalog(params)
    return not catalog.HasMatch(rdkit_mol)


def compute_qed_sas(rdkit_mol) -> tuple[float, float]:
    """Return `(QED, SAScore)` for a molecule.

    SAScore lives in RDKit's contrib SA_Score directory and isn't on the
    public path — this helper handles the `sys.path.append` ritual.
    """
    import sys

    from rdkit.Chem import QED, RDConfig  # lazy

    sa_dir = f"{RDConfig.RDContribDir}/SA_Score"
    if sa_dir not in sys.path:
        sys.path.append(sa_dir)
    import sascorer

    return float(QED.qed(rdkit_mol)), float(sascorer.calculateScore(rdkit_mol))


__all__ = [
    "SMARTS_ALERTS",
    "check_smarts_alerts",
    "compute_qed_sas",
    "mol_to_rdkit",
    "pains_brenk_nih_filter",
    "rdkit_to_mol",
    "smiles_to_mol",
]
